---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: base-goss-centos7
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: base-goss-centos6
    image: centos:6
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: base-goss-ubuntu
    image: ubuntu
    privileged: True
  - name: base-goss-debian9
    image: debian:stretch
    privileged: True
  - name: base-goss-debian10
    image: debian:buster
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
